const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[],writes=[];
 page.on('pageerror',e=>errors.push(e.message));
 const rows=[['Z1','ZETA'],['A2','ALPHA'],['A1','alpha'],['Z2','ZETA'],['U1','']].map(([id,firm])=>({id:'rec'+id,fields:{id,firm,CurrentBalance:52000}}));
 const queue={rows:[{id:'PAIR-1',status:'Waiting',dispatched:true,spec:{left:'a',right:'b',masters:{a:'ALPHA',b:'ZETA'},accounts:{a:'A1',b:'Z1'},balances:{a:52000,b:53000},quantities:{a:2,b:3},ratio:'2:3',profit:500,stopLoss:600,ticker:'NQ DEC26'}}],history:[],running:true};
 const fleet=[{id:'a',name:'ALPHA',online:true,fresh:true,position:'Flat',accounts:['A1'],refresh:{status:'complete',message:'Accounts refreshed. 1 matched account.'}}];
 await page.route('http://127.0.0.1:8788/**',async route=>{
  const req=route.request(),url=new URL(req.url());let result;
  if(req.method()==='POST'){writes.push(url.pathname);result={ok:true};}
  else if(url.pathname==='/api/state')result={version:'16.0-preview.34',fleet,pairs:[],events:[],vmEvents:[],limits:{vms:50,pairs:20}};
  else if(url.pathname==='/api/planning')result={rows,columns:['id','firm','CurrentBalance'].map(name=>({name})),updatedAt:1,busy:false,error:''};
  else if(url.pathname==='/api/queue')result=queue;
  else if(url.pathname==='/api/contracts')result={month:'DEC26',symbols:{NQ:'NQ DEC26',MNQ:'MNQ DEC26'}};
  if(result)return route.fulfill({json:result});
  const file=url.pathname==='/'?'index.html':url.pathname.slice(1);
  await route.fulfill({body:fs.readFileSync(path.join(__dirname,'../coordinator/static',file)),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});
 });
 await page.goto('http://127.0.0.1:8788/#'+'a'.repeat(64));await page.locator('.vm-list-row').waitFor();
 assert.ok((await page.locator('header').boundingBox()).height<=50);
 assert.ok((await page.locator('#tab-vms').boundingBox()).y<230);
 assert.ok((await page.locator('.vm-list-row').boundingBox()).height<90);
 assert.equal(await page.locator('.vm-row-secondary p').textContent(),'Accounts refreshed. 1 matched account.');
 await page.locator('#tab-planning').click();await page.locator('#planning-table tbody tr[data-record]').first().waitFor();
 assert.ok(!(await page.locator('#planning-table thead').textContent()).includes('Order'));
 assert.equal(await page.locator('#suggestion-strategy option:checked').textContent(),'Test Non-consitency');
 assert.equal(await page.locator('#suggestion-info').getAttribute('open'),null);
 const selection=await page.locator('#planning-select-all').boundingBox(),hide=await page.locator('#planning-column-options').boundingBox(),batch=await page.locator('#draft-add-all').boundingBox(),strategy=await page.locator('.suggestion-beta').boundingBox();
 assert.ok(selection.y>=hide.y+hide.height);assert.ok(selection.height<=28);assert.equal(batch.height,selection.height);assert.ok(batch.y>=strategy.y+strategy.height);assert.ok(strategy.height<100);
 await page.locator('#planning-group-fund').click();
 assert.deepEqual(await page.locator('.fund-heading').allTextContents(),['ALPHA','ZETA','Unspecified fund']);
 assert.equal(await page.locator('#planning-table tbody .planning-column-header').count(),3);
 const accountOrder=()=>page.locator('#planning-table tr[data-record]').evaluateAll(rs=>rs.map(r=>r.dataset.account));
 assert.deepEqual(await accountOrder(),['A2','A1','Z1','Z2','U1']);
 await page.locator('#planning-table tbody .planning-column-header').first().getByRole('button',{name:'id',exact:true}).click();
 assert.deepEqual(await accountOrder(),['A1','A2','Z1','Z2','U1']);
 await page.getByRole('checkbox',{name:'Select A2',exact:true}).check();await page.getByRole('checkbox',{name:'Select Z2',exact:true}).click({modifiers:['Shift']});
 assert.equal(await page.locator('#planning-table tbody input:checked').count(),3);
 await page.locator('#planning-select-all').click();assert.equal(await page.locator('#planning-table tbody input:checked').count(),5);
 await page.locator('#planning-clear-selection').click();assert.equal(await page.locator('#planning-table tbody input:checked').count(),0);
 const header=page.locator('#planning-table tbody .planning-column-header').first();
 const before=(await header.getByRole('columnheader',{name:'firm',exact:true}).boundingBox()).width;
 await header.getByRole('separator',{name:'Resize firm',exact:true}).focus();await page.keyboard.press('ArrowRight');
 for(const h of await page.locator('#planning-table tbody .planning-column-header').all())assert.ok((await h.getByRole('columnheader',{name:'firm',exact:true}).boundingBox()).width>=before+9);
 await header.getByRole('columnheader',{name:'CurrentBalance',exact:true}).dragTo(header.getByRole('columnheader',{name:/^id/}));
 assert.deepEqual(await page.locator('#planning-table tbody .planning-column-header').first().locator('th').allTextContents(),['Select','CurrentBalance','Pair status','id ↑','firm']);
 await page.reload();await page.locator('#tab-planning').click();await page.locator('.fund-heading').first().waitFor();
 assert.equal(await page.locator('#planning-group-fund').getAttribute('aria-pressed'),'true');
 assert.deepEqual(await accountOrder(),['A1','A2','Z1','Z2','U1']);
 await page.locator('#planning-group-fund').click();assert.equal(await page.locator('.fund-heading').count(),0);
 await page.locator('#tab-trading').click();const table=page.locator('#trading-queue-table');await table.locator('tr[data-pair]').waitFor();
 assert.equal(await table.locator('td[data-column="3"] .pair-settings').textContent(),'P $500 L $600');
 assert.equal(await table.locator('td[data-column="5"] .pair-settings').textContent(),'P $900 L $750');
 assert.equal((await table.locator('input[type=checkbox]').boundingBox()).width,16);
 assert.ok((await page.locator('#trading-date').boundingBox()).height<32);
 await table.locator('th[data-column="5"]').dragTo(table.locator('th[data-column="2"]'));
 assert.deepEqual(await table.locator('thead th').evaluateAll(hs=>hs.map(h=>+h.dataset.column)),[0,1,5,2,3,4,6,7,8,9,10,11]);
 assert.equal(await table.locator('tr[data-pair] td').nth(2).locator('.pair-settings').textContent(),'P $900 L $750');
 await table.locator('th[data-column="5"] button').click();assert.equal(await table.locator('th[data-column="5"]').getAttribute('aria-sort'),'ascending');
 await page.reload();await page.locator('#tab-trading').click();await table.locator('tr[data-pair]').waitFor();
 assert.equal(await table.locator('thead th').nth(2).getAttribute('data-column'),'5');
 assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
 await browser.close();console.log('PASS: compact layout, grouped fund headers and sorting, Shift range selection, shared widths, saved grouping/columns, strategy disclosure, configured amounts and ratio, Trading column persistence, no trading writes.');
})().catch(e=>{console.error(e);process.exit(1)});
