// Run with NODE_PATH pointing to an installed Playwright package.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.TCC_BROWSER_PATH||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:850}}),errors=[],writes=[];
 page.on('pageerror',e=>errors.push(e.message));
 let snapshot={rows:[{id:'a',fields:{id:'A',Balance:100}},{id:'b',fields:{id:'B',Balance:9}}],columns:[{name:'id',type:'singleLineText'},{name:'Balance',type:'currency'}],updatedAt:1,busy:false,error:'',configured:true};
 await page.route('http://127.0.0.1:8788/**',async route=>{
  const req=route.request(),url=new URL(req.url());
  let result;
  if(req.method()==='POST'){
   writes.push(url.pathname);assert.equal(url.pathname,'/api/planning/refresh','Planning must not send trading commands');
   snapshot={...snapshot,updatedAt:snapshot.updatedAt+1,rows:[...snapshot.rows,{id:'c',fields:{id:'C',Balance:20}}].filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i)};result={ok:true};
  }else if(url.pathname==='/api/state')result={fleet:[],pairs:[],events:[]};
  else if(url.pathname==='/api/queue')result={rows:[],running:false,message:'Paused'};
  else if(url.pathname==='/api/planning')result=snapshot;
  if(result)return route.fulfill({json:result});
  const file=url.pathname==='/'?'index.html':url.pathname.slice(1);
  const contentType=file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html';
  await route.fulfill({body:fs.readFileSync(path.join(__dirname,'../coordinator/static',file)),contentType});
 });
 await page.goto('http://127.0.0.1:8788/#'+'a'.repeat(64));
 await page.locator('#tab-planning').click();
 await page.locator('#planning-table tbody tr').first().waitFor();
 const accounts=()=>page.locator('#planning-table tbody tr td:nth-child(4)').allTextContents();
 assert.deepEqual(await accounts(),['A','B']);
 await page.locator('#planning-table tbody tr').first().dragTo(page.locator('#planning-table tbody tr').nth(1));
 assert.deepEqual(await accounts(),['B','A']);
 await page.getByRole('button',{name:'Balance',exact:true}).click();
 assert.deepEqual(await accounts(),['B','A']);
 await page.getByRole('button',{name:'Balance ↑',exact:true}).click();
 assert.deepEqual(await accounts(),['A','B']);
 await page.locator('#planning-manual').click();
 assert.deepEqual(await accounts(),['B','A']);
 await page.locator('#planning-panel summary').click();
 await page.getByRole('checkbox',{name:'Balance',exact:true}).uncheck();
 assert.equal(await page.locator('#planning-table th').count(),4);
 await page.locator('#planning-refresh').click();
 await page.waitForFunction(()=>document.querySelectorAll('#planning-table tbody tr').length===3);
 assert.deepEqual(await accounts(),['B','A','C']);
 await page.reload();await page.locator('#tab-planning').click();
 await page.waitForFunction(()=>document.querySelectorAll('#planning-table tbody tr').length===3);
 assert.deepEqual(await accounts(),['B','A','C']);
 assert.equal(await page.locator('#planning-table th').count(),4);
 await page.locator('#planning-table tbody tr').nth(2).dragTo(page.locator('#planning-table tbody tr').first());
 assert.deepEqual(await accounts(),['C','B','A']);
 await page.locator('#planning-panel summary').click();
 await page.getByRole('checkbox',{name:'Balance',exact:true}).check();
 await page.getByRole('columnheader',{name:'Balance',exact:true}).dragTo(page.getByRole('columnheader',{name:'id',exact:true}));
 const balanceHeader=page.getByRole('columnheader',{name:'Balance',exact:true});
 const originalWidth=(await balanceHeader.boundingBox()).width;
 const handle=await page.getByRole('separator',{name:'Resize Balance',exact:true}).boundingBox();
 await page.mouse.move(handle.x+4,handle.y+12);await page.mouse.down();await page.mouse.move(handle.x+104,handle.y+12);await page.mouse.up();
 assert.ok((await balanceHeader.boundingBox()).width>=originalWidth+95);
 await page.locator('#planning-save-view').click();
 assert.equal(await page.locator('#view-save-status').textContent(),'View saved');
 assert.deepEqual(await page.locator('#planning-table thead th').allTextContents(),['Select','Order','Balance','Pair status','id']);
 await page.reload();await page.locator('#tab-planning').click();
 await page.waitForFunction(()=>document.querySelectorAll('#planning-table tbody tr').length===3);
 assert.deepEqual(await page.locator('#planning-table thead th').allTextContents(),['Select','Order','Balance','Pair status','id']);
 await page.locator('#tab-trading').click();assert.equal(await page.locator('#trading-panel').isVisible(),true);
 await page.locator('#tab-planning').click();
 snapshot={...snapshot,updatedAt:99,columns:[...snapshot.columns,{name:'Realized PnL',type:'currency'}],rows:snapshot.rows.map((r,i)=>({...r,fields:{...r.fields,'Realized PnL':[-100,200,0][i]}}))};
 await page.waitForFunction(()=>document.querySelectorAll('#planning-table .pnl-negative').length===1);
 assert.equal(await page.locator('#planning-table .pnl-negative').textContent(),'-100');
 assert.equal(await page.locator('#planning-table .pnl-positive').textContent(),'200');
 assert.equal(await page.locator('#planning-table .pnl-negative').evaluate(e=>getComputedStyle(e).color),'rgb(180, 35, 50)');
 assert.equal(await page.locator('#planning-table .pnl-positive').evaluate(e=>getComputedStyle(e).color),'rgb(20, 116, 71)');
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).colorScheme),'light');
 await page.screenshot({path:'/tmp/planning-preview13.png',fullPage:true});
 assert.ok((await page.getByRole('columnheader',{name:'Balance',exact:true}).boundingBox()).width>=originalWidth+95);
 assert.deepEqual(errors,[]);assert.deepEqual(writes,['/api/planning/refresh']);
 await browser.close();console.log('Planning browser: sort, hide, refresh, persistence, drag, tabs and trading-command isolation passed.');
})().catch(e=>{console.error(e);process.exit(1)});
