const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync('coordinator/static/draft-payload.js','utf8'),context);
const metrics={CurrentBalance:52718.48,'Realized PnL':-25,stop:48500,'Trailing max drawdown':1500,largestProfitDay:200,tradingDays:2,notes:'x'.repeat(40000),attachments:[{url:'https://unused.example'}]};
const draft={key:'a'.repeat(32),ticker:'NQ',ratio:'1:1',direction:'buy',leftQuantity:'1',rightQuantity:'1',profit:'350',stopLoss:'400',rightProfit:'400',rightStopLoss:'350',left:{account:'FFF236159',master:'FFF-TRINH',vm:'left',record:'recA',balance:52718.48,metrics},right:{account:'FNFTC',master:'FN-JASON',vm:'right',record:'recB',balance:52157.48,metrics},error:'Invalid request size.',extra:'x'.repeat(40000)};
const clean=context.compactPairDraft(draft);assert.ok(Buffer.byteLength(JSON.stringify({draft:clean}))<4000);assert.equal(clean.left.metrics['Realized PnL'],-25);assert.equal(clean.left.metrics.notes,undefined);assert.equal(clean.error,undefined);assert.equal(clean.ticker,'NQ');assert.equal(clean.leftQuantity,'1');assert.equal(clean.rightStopLoss,'350');assert.equal(clean.left.vm,'left');assert.equal(clean.left.account,draft.left.account);assert.equal(clean.left.record,'recA');assert.equal(clean.extra,undefined);
const single=context.compactPairDraft({...draft,right:null});assert.equal(single.right,undefined);assert.ok(single.left);
assert.equal(draft.left.metrics.notes.length,40000);console.log('PASS: large Airtable records stay below request limit; editable quantities, targets and displayed metrics retained; single pairs supported.');

context.PairSuggestions=require('../coordinator/static/suggestions.js');
const suggested={...draft,suggestion:{strategy:'non-consistency-tests',revision:33,reason:'test'},left:{...draft.left,metrics:{...metrics,firm:'FFF',InitialBalance:52500,balance:52600,CurrentProfit:2600,ProfitTarget:3000,Consistency:0}}};
const packed=context.compactPairDraft(suggested);assert.equal(packed.suggestion.revision,33);assert.equal(packed.left.metrics.InitialBalance,52500);assert.equal(packed.left.metrics.balance,52600);assert.equal(packed.left.metrics['Realized PnL'],-25);assert.ok(Buffer.byteLength(JSON.stringify(packed))<8000);
